name: iOS Build & Test

on:
  push:
    paths:
      - 'ios/**'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'ios/**'

jobs:
  build:
    runs-on: macos-14 

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Lister les versions Xcode installées
        run: ls /Applications | grep Xcode

      - name: Sélectionner Xcode 16.2
        run: |
          sudo xcode-select -s /Applications/Xcode_16.2.app
          xcodebuild -version
          sudo xcode-select -p

      - name: Vérifier les runtimes iOS disponibles
        run: xcrun simctl list runtimes

      - name: Vérifier les simulateurs disponibles
        run: xcrun simctl list devices

      - name: Récupérer l’UDID du simulateur iPhone 16 Pro
        run: |
          UDID=$(xcrun simctl list devices | grep "iPhone 16 Pro (" | grep "OS:18.2" | grep -oE '[0-9A-F\-]{36}' | head -n 1)
          if [[ -z "$UDID" ]]; then
            echo "Erreur : Aucun simulateur iPhone 16 Pro sous iOS 18.2 trouvé."
            exit 1
          fi
          echo "UDID=$UDID" >> $GITHUB_ENV
          echo "UDID sélectionné : $UDID"

      - name: Démarrer le simulateur iPhone 16 Pro
        run: |
          echo "Démarrage du simulateur avec UDID: $UDID"
          xcrun simctl boot "$UDID"
          sleep 15

      - name: Vérifier la présence du projet
        run: |
          ls -R ios 

      - name: Build et Test de l'application
        run: |
          cd ios
          echo "Compilation avec UDID: $UDID"
          xcodebuild -project Ticky.xcodeproj -scheme Ticky -destination "id=$UDID" clean build test