name: iOS Build & Test

on:
  push:
    paths:
      - 'ios/**'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'ios/**'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Vérifier la version d'Xcode
        run: xcodebuild -version

      - name: Build de l'application
        run: |
          cd ios
          xcodebuild -workspace Ticky.xcworkspace -scheme Ticky -destination 'platform=iOS Simulator,name=iPhone 16 Pro' clean build

      - name: Lancer les tests
        run: |
          cd ios
          xcodebuild test -workspace Ticky.xcworkspace -scheme Ticky -destination 'platform=iOS Simulator,name=iPhone 16 Pro'

      - name: Vérifier la qualité du code (SwiftLint)
        run: |
          cd ios
          if which swiftlint > /dev/null; then
            swiftlint
          else
            echo "SwiftLint n'est pas installé"
          fi