name: iOS Build & Test

on:
  push:
    paths:
      - 'ios/**'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'ios/**'

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Lister les versions Xcode installées
        run: ls /Applications | grep Xcode

      - name: Sélectionner Xcode 16.2
        run: |
            sudo xcode-select -s /Applications/Xcode_16.2.app
            sudo xcode-select -p
            xcodebuild -version

      - name: Vérifier la version d'Xcode
        run: xcodebuild -version

      - name: Démarrer un simulateur iPhone 16 Pro
        run: |
          UDID=$(xcrun simctl list devices | grep "iPhone 16 Pro (" | grep -oE '[0-9A-F\-]{36}' | head -n 1)
          echo "Utilisation du simulateur avec UDID: $UDID"
          xcrun simctl boot "$UDID"
          sleep 15

      - name: Build de l'application
        run: |
          cd ios
          xcodebuild -project Ticky.xcodeproj -scheme Ticky -destination "platform=iOS Simulator,OS=latest,name=iPhone 16 Pro" clean build