name: iOS Build & Test

on:
  push:
    paths:
      - 'ios/**'
  pull_request:
    paths:
      - 'ios/**'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Vérifier la version d'Xcode
        run: xcodebuild -version

      - name: Build et Test de l'application
        run: |
          cd ios
          # Adapte la commande suivante en fonction de ta configuration (workspace, scheme, etc.)
          xcodebuild -workspace ios/Ticky.xcodeproj/project.xcworkspace -scheme Ticky -destination 'platform=iOS Simulator,name=iPhone 16 Pro' clean build